-- MySQL Script generated by MySQL Workbench
-- mer. 05 janv. 2022 16:20:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BlindTest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BlindTest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BlindTest` DEFAULT CHARACTER SET utf8 ;
USE `BlindTest` ;

-- -----------------------------------------------------
-- Table `BlindTest`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BlindTest`.`User` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BlindTest`.`Reponse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BlindTest`.`Reponse` (
  `value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`value`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BlindTest`.`Fichier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BlindTest`.`Fichier` (
  `idFichier` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `extension` VARCHAR(45) NULL,
  `Reponse_value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFichier`, `Reponse_value`),
  INDEX `fk_Fichier_Reponse_idx` (`Reponse_value` ASC) VISIBLE,
  CONSTRAINT `fk_Fichier_Reponse`
    FOREIGN KEY (`Reponse_value`)
    REFERENCES `BlindTest`.`Reponse` (`value`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
